#!/bin/bash

# Print mean, median, min, max of abs(TLEN)
# Requires: R, samtools, awk

samtools view $1 | awk '{if($9 < 10000) {print $9}}' | head -10000 | Rscript <(echo '
d<-scan("stdin", quiet=TRUE)
d<-abs(d)
cat("min:",min(d),"\n",sep="")
cat("max:",max(d),"\n",sep="")
cat("median:",median(d),"\n",sep="")
cat("mean:",mean(d),"\n",sep="")
')
