#!/bin/bash

set -eou pipefail

#
# Get A,C,G,T base counts from `samtools mpileup`
# Requires: samtools awk
#

samtools mpileup $@ | awk '{
c["a"] = c["A"] = 0
c["c"] = c["C"] = 0
c["g"] = c["G"] = 0
c["t"] = c["T"] = 0
for(i = 1; i <= length($5); i+=1) {
  c[substr($5,i,1)] += 1
}
print $1,$2,$3,$4,(c["a"]+c["A"]), (c["c"]+c["C"]), (c["g"]+c["G"]), (c["t"]+c["T"])
}'
