#!/bin/bash

#
# Print VCF header and entries that PASS -- e.g. if their filter column is
# 'PASS' or '.'. Works with .vcf, .vcf.gz and piped input.
#

gzip -fcd $1 | awk '$1 ~ /^#/ || $7 ~ /^(PASS|\.)$/'
